baseURL = 'https://ufxpri.github.io/'
languageCode = 'en-us'
title = 'Minimal Blog'

[params]
  description = 'Typography driven, feature-rich blogging theme with minimal aesthetics'
  author = 'Jo Seungjun'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[menu]
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 3
